# Generated by Django 4.2.7 on 2024-01-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='sub_total',
        ),
    ]
