# Generated by Django 4.2.7 on 2024-01-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_subtotal_orderitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
