# Generated by Django 4.2.7 on 2024-01-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_orders_status_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.menuitem'),
        ),
    ]
