# Generated by Django 4.2.7 on 2024-01-26 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_orders_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.menuitem'),
        ),
    ]
