# Generated by Django 4.2.7 on 2024-02-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_menuitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='category_name',
        ),
    ]
