# Generated by Django 4.2.7 on 2024-02-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_category_menuitem_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category_name',
            new_name='category',
        ),
    ]
